# import os

AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
AWS_REGION = "us-east-1"

# S3
S3_INPUT_BUCKET_NAME = "S3_INPUT_BUCKET_NAME"
S3_OUTPUT_BUCKET_NAME = "S3_OUTPUT_BUCKET_NAME"

# SQS
SQS_REQUEST_QUEUE_URL = "SQS_REQUEST_QUEUE_URL"
SQS_RESPONSE_QUEUE_URL = "SQS_RESPONSE_QUEUE_URL"

# Directories
UPLOAD_FOLDER = "uploaded_images"

# Response timeout
TIMEOUT = 1000000